export const HTTP_STATUS_CODE = {
  OK: 200,
  UPDATED: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  DEFAULT_ERROR: 418,
  INTERNAL_SERVER_ERROR: 500,
};

export const SERVER_PORT_CONNECTION = 3003;

export const BOUNDARY_RADIUS_IN_METERS = 1000;

export const BOUNDARY_NUM_SIDES = 32;

export const NEARBY_MAX_DISTANCE_IN_METERS = 5000;
